server.port=8080

spring.datasource.url=${REFERREE_DB_URL:jdbc:h2:mem:r3f3r;DB_CLOSE_DELAY=-1;MODE=Oracle}
spring.datasource.username=${REFERREE_DB_USER:sa}
spring.datasource.password=${REFERREE_DB_PASSWORD:}
spring.datasource.driver-class-name=${REFERREE_DB_DRIVER:org.h2.Driver}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=${REFERREE_DB_DIALECT:org.hibernate.dialect.H2Dialect}
